export const ENEMY_REACTION_LINES = [
  "Ouchhhh!",
  "Ooof!",
  "That hurts!",
  "That stings!",
  "Yow!",
  "Yikes!",
  "Ack!",
  "Argh!",
  "Gah!",
  "Whoa!",
  "Hey!",
  "Stop!",
  "Don't do that!",
  "Cut it out!",
  "Not cool!",
  "Seriously?!",
  "Come on!",
  "No fair!",
  "Uncool!",
  "That was rude!",
  "Ow ow!",
  "Good grief!",
  "Sheesh!",
  "Mercy!",
  "I felt that!",
  "Not nice!",
  "You made me jump!",
  "Watch it!",
  "Easy!",
  "Ow! Okay, okay!",
  "Alright, enough!",
  "That's uncalled for!",
  "Oof, that was close!",
  "Ugh!",
  "Argh, really?",
  "Not again!",
  "Give me a break!",
  "Whoa, watch out!",
  "That smarts!",
  "Ow! I'm not made of stone!",
  "That's gonna leave a mark!",
  "Noooo!",
  "Grr!",
  "You little—!",
  "I'll get you back!",
  "You shouldn't have!",
  "This isn't over!",
  "Yowch!",
  "That's low!",
  "Not on my watch!",
  "Mind your manners!",
  "Easy there!",
  "You've got some nerve!",
  "That's enough!",
  "Ow! Payback!",
  "Oh, come off it!",
  "I need a healer!",
  "That's harsh!",
  "Hey, that's cheap!",
  "Don't make me angry!",
  "You're pushin' it!",
  "Back off!",
  "I'm hit!",
  "Fine, be that way!",
  "You asked for that!",
  "Try that again!",
  "Nice one... not.",
  "You're going down!",
  "Not cool, pal!",
  "Wow, rude move!",
  "Can't believe that!",
  "That took me by surprise!",
  "Whoa, too quick!",
  "That's over the line!",
  "I'll remember that!",
  "You'll regret this!",
  "Ow! Pretty rough!",
  "Okay, I surrender... maybe.",
  "That's on you!",
];
