export const ENEMY_REACTION_LINES = [
  "Ouchhhh!",
  "Ooof!",
  "That hurts!",
  "That stings!",
  "Yow!",
  "Yikes!",
  "Ack!",
  "Argh!",
  "Gah!",
  "Whoa!",
  "Hey!",
  "Stop!",
  "Don't do that!",
  "Cut it out!",
  "Not cool!",
  "Seriously?!",
  "Come on!",
  "No fair!",
  "Uncool!",
  "That was rude!",
  "Ow ow!",
  "Good grief!",
  "Sheesh!",
  "Mercy!",
  "I felt that!",
  "Not nice!",
  "You made me jump!",
  "Watch it!",
  "Easy!",
  "Ow! Okay, okay!",
  "Alright, enough!",
  "That's uncalled for!",
  "Oof, that was close!",
  "Ugh!",
  "Argh, really?",
  "Not again!",
  "Give me a break!",
  "Whoa, watch out!",
  "That smarts!",
  "Ow! I'm not made of stone!",
  "That's gonna leave a mark!",
  "Noooo!",
  "Grr!",
  "You little—!",
  "I'll get you back!",
  "You shouldn't have!",
  "This isn't over!",
  "Yowch!",
  "That's low!",
  "Not on my watch!",
  "Mind your manners!",
  "Easy there!",
  "You've got some nerve!",
  "That's enough!",
  "Ow! Payback!",
  "Oh, come off it!",
  "I need a healer!",
  "That's harsh!",
  "Hey, that's cheap!",
  "Don't make me angry!",
  "You're pushin' it!",
  "Back off!",
  "I'm hit!",
  "Fine, be that way!",
  "You asked for that!",
  "Try that again!",
  "Nice one... not.",
  "You're going down!",
  "Not cool, pal!",
  "Wow, rude move!",
  "Can't believe that!",
  "That took me by surprise!",
  "Whoa, too quick!",
  "That's over the line!",
  "I'll remember that!",
  "You'll regret this!",
  "Ow! Pretty rough!",
  "Okay, I surrender... maybe.",
  "That's on you!",
];

export const CHARACTER_CORRECT_REACTIONS = [
  "You deserved that!",
  "Take that!",
  "That's what you get!",
  "Serves you right!",
  "That ones for you!",
  "Got what was coming!",
  "Consider that served!",
  "Right where it counts!",
  "Told you so!",
  "Nice and fair!",
  "That's how it's done!",
  "You asked for that!",
  "Hope you learned your lesson!",
  "Exactly what I expected!",
  "Score one for me!",
  "All in a day's work!",
  "That's on you!",
  "Payback time!",
  "Gotcha good!",
  "Consider yourself warned!",
  "That's the outcome!",
  "Perfectly deserved!",
  "Mission accomplished!",
  "You couldn't dodge that!",
  "That hit the mark!",
  "Exactly as planned!",
  "That settles it!",
  "You've been served!",
  "I meant every bit of that!",
  "Point for me!",
  "That's one down!",
  "Right on cue!",
  "That was inevitable!",
  "No sympathy!",
  "Took you out!",
  "That was satisfying!",
  "Checkmate!",
  "All wrapped up!",
  "That's victory!",
];

export const CHARACTER_WRONG_REACTIONS = [
  "My bad!",
  "That was on me!",
  "Oops, missed!",
  "I blew it!",
  "Not my best move!",
  "I misread that!",
  "Wrong choice!",
  "Dang, that failed!",
  "I dropped the ball!",
  "That backfired!",
  "I messed up!",
  "Should've seen that!",
  "That's embarrassing!",
  "Uh — that wasn't right!",
  "I take the hit!",
  "Wrong move, sorry!",
  "I goofed!",
  "Aw, bad timing!",
  "I should've waited!",
  "That was a mistake!",
  "I flubbed that one!",
  "My timing's off!",
  "I slipped up!",
  "That didn't work!",
  "Okay, my fault!",
  "Not how I planned!",
  "That was clumsy!",
  "I guessed wrong!",
  "Scratch that, my mistake!",
  "I'll fix it next time!",
  "I misplayed it!",
  "That was sloppy!",
  "Oops — not good!",
  "I read it wrong!",
  "That was careless!",
  "I underestimated it!",
  "I'll do better!",
  "Wrong call!",
  "Back to the drawing board!",
];
