export const ENEMY_WRONG_LINES = [
  "Ouchhhh!",
  "Ooof! My health bar!",
  "That hurts! What a hit!",
  "Yow! Critical damage!",
  "Yikes! I didn't see that coming!",
  "Ack! My defenses!",
  "Argh! Right in the code block!",
  "Gah! I'm glitching!",
  "Whoa! Too fast!",
  "Hey! That actually hurt!",
  "Stop! You're breaking my code!",
  "Don't do that!",
  "Cut it out!",
  "Not cool!",
  "Seriously?!",
  "Come on!",
  "No fair! That hit too hard!",
  "Uncool! I wasn't ready!",
  "That was rude!",
  "Ow ow! Okay, I yield!",
  "Good grief! What an attack!",
  "Mercy! I felt that!",
  "Not nice!",
  "You made me jump!",
  "Watch it!",
  "Easy! I'm taking damage here!",
  "Ow! Okay, okay!",
  "Alright, enough!",
  "That's uncalled for!",
  "Oof, that was close!",
  "Ugh! Direct hit!",
  "Argh, really?",
  "Not again!",
  "Give me a break!",
  "Whoa, watch out!",
  "That smarts!",
  "Ow! I'm not made of stone!",
  "That's gonna leave a mark!",
  "Noooo! My HP!",
  "Grr! You'll pay for that!",
  "You little—!",
  "I'll get you back!",
  "You shouldn't have done that!",
  "This isn't over!",
  "Yowch!",
  "That's low!",
  "Not on my watch!",
  "Mind your manners!",
  "Easy there!",
  "You've got some nerve!",
  "That's enough!",
  "Ow! Payback is coming!",
  "Oh, come off it!",
  "I need a healer!",
];

export const ENEMY_CORRECT_LINES = [
  "The {wrong_answer} makes me overpower to attack you!",
  "Did you really think {wrong_answer} would hurt me?",
  "Ha! Your {wrong_answer} only makes me stronger!",
  "You call {wrong_answer} an attack? Pathetic!",
  "I feed on mistakes like {wrong_answer}!",
  "Serves you right for trying to use {wrong_answer}!",
  "Take that! {wrong_answer} wouldn't even hurt a fly!",
  "That's what you get for relying on {wrong_answer}!",
  "You got what was coming! {wrong_answer} is a joke!",
  "Right where it counts! Thanks for the {wrong_answer}!",
  "Too slow! I saw that {wrong_answer} coming a mile away!",
  "Payback time! I deflect {wrong_answer} all day long!",
  "Gotcha! A toddler could code better than {wrong_answer}!",
  "Another one down! {wrong_answer} is practically helping me win!",
  "Couldn't dodge that? Your {wrong_answer} is full of bugs!",
  "Winners do this! Losers use {wrong_answer}!",
  "Not so brave now that your {wrong_answer} failed, huh?",
  "Consider that served! {wrong_answer} was a free power-up!",
  "Eat that! Next time, try something harder than {wrong_answer}!",
  "Feel that! {wrong_answer} is just weak!",
  "Better luck next time! Drop the {wrong_answer} strategy!",
  "That's the price for typing {wrong_answer}!",
  "Justice served against your {wrong_answer}!",
  "Told you so! {wrong_answer} never works!",
  "All in a day's work crushing your {wrong_answer}!",
  "Now who's laughing at {wrong_answer}?",
  "Too easy! I block {wrong_answer} with my eyes closed!",
  "Outclassed! {wrong_answer} is an amateur move!",
  "Outplayed! Did you actually type {wrong_answer}?",
  "Dominated! Keep using {wrong_answer}, it makes me laugh!",
  "Humiliating, isn't it? {wrong_answer} failed completely!",
  "Crushing blow! Your {wrong_answer} syntax error is your doom!",
  "Game over for your {wrong_answer}!",
  "I warned you about using {wrong_answer}!",
  "Consider yourself owned by {wrong_answer}!",
];

export const CHARACTER_CORRECT_REACTIONS = [
  "You deserved that! Perfect execution!",
  "Take that! Debugged you right out of existence!",
  "That's what you get for messing with my code!",
  "Serves you right! My logic is flawless!",
  "That one's for you! No syntax errors here!",
  "Got what was coming! Clean code always wins!",
  "Consider that served! Compiled and executed!",
  "Right where it counts! Critical hit!",
  "Told you so! I read you like an open source file!",
  "Nice and fair! No hacks needed!",
  "That's how it's done! Flawless victory!",
  "You asked for that! Should've checked my stats!",
  "Hope you learned your lesson! Don't mess with me!",
  "Exactly what I expected! Perfect algorithm!",
  "Score one for me! Right on target!",
  "All in a day's work! Bug exterminated!",
  "Payback time! That executed perfectly!",
  "Gotcha good! No escaping that loop!",
  "Consider yourself warned! I'm just warming up!",
  "Perfectly deserved! That hit the mark!",
  "Mission accomplished! Another bug squashed!",
  "You couldn't dodge that! My aim is true!",
  "Exactly as planned! I control the logic here!",
  "That settles it! You're officially outclassed!",
  "You've been served a fatal exception!",
  "I meant every bit of that!",
  "Point for me! Easy as pie!",
  "That's one down! Who's next?",
  "Right on cue! Executed without a hitch!",
  "That was inevitable! I always win!",
  "No sympathy for glitches like you!",
  "Took you out! Consider yourself deleted!",
  "That was satisfying! Code runs perfectly!",
  "Checkmate! You're out of moves!",
  "All wrapped up! Deployment successful!",
  "That's victory! Enjoy the defeat!",
];

export const CHARACTER_WRONG_REACTIONS = [
  "{player_name}, check line {line_number} again!",
  "Ouch! Let's review line {line_number}, {player_name}.",
  "That hit hard! {player_name}, something is wrong at line {line_number}.",
  "Oops, missed! {player_name}, you need to inspect line {line_number}.",
  "We blew it! {player_name}, is there a typo on line {line_number}?",
  "Not our best move! Time to debug line {line_number}, {player_name}.",
  "{player_name}, we misread that! Let's re-examine line {line_number}.",
  "Wrong choice, {player_name}! The error must be on line {line_number}.",
  "Dang, that failed! {player_name}, we dropped the ball on line {line_number}.",
  "That backfired! {player_name}, something's off at line {line_number}.",
  "We messed up! Let's audit line {line_number} again, {player_name}.",
  "{player_name}, we should've seen that! Line {line_number} needs a fix.",
  "That's embarrassing! {player_name}, let's correct line {line_number}.",
  "Uh — that wasn't right! {player_name}, look closely at line {line_number}.",
  "I'm taking hits here! {player_name}, quick, fix line {line_number}!",
  "Wrong move! Let's pinpoint line {line_number}, {player_name}.",
  "We goofed, {player_name}! Bad logic on line {line_number}.",
  "Aw, bad timing! {player_name}, try re-checking line {line_number}.",
  "We moved too fast! {player_name}, let's review line {line_number}.",
  "That was a mistake! {player_name}, check what's wrong on line {line_number}.",
  "We flubbed that one! Focus on line {line_number}, {player_name}.",
  "Our timing's off! Back to line {line_number}, {player_name}.",
  "We slipped up! {player_name}, line {line_number} is the culprit.",
  "That didn't work, {player_name}! Let's revise line {line_number}.",
  "Okay, {player_name}! Try re-reading line {line_number}.",
  "Not how we planned! {player_name}, the bug is hiding on line {line_number}.",
  "That was clumsy! {player_name}, double-check line {line_number}.",
  "We guessed wrong! {player_name}, let's figure out line {line_number}.",
  "Scratch that, {player_name}! Back to line {line_number}.",
  "We'll fix it next time! {player_name}, start with line {line_number}.",
  "We misplayed it! {player_name}, is there a syntax error on line {line_number}?",
  "That was sloppy! Let's clean up line {line_number}, {player_name}.",
  "Oops — not good! {player_name}, check the logic on line {line_number}.",
  "{player_name}, we read it wrong! Let's look at line {line_number} one more time.",
  "That was careless, {player_name}! We underestimated line {line_number}.",
  "We can do better, {player_name}! Start by fixing line {line_number}.",
  "Wrong call! Let's adjust line {line_number}, {player_name}.",
  "Back to the drawing board, {player_name}! Let's start with line {line_number}.",
];

export const CHARACTER_MISMATCHED_TAG_REACTIONS = [
  "{player_name}, {wrong_open_tag} is not a perfect pair for {wrong_close_tag} on line {line_number}!",
  "Oops! {player_name}, you can't close {wrong_open_tag} with {wrong_close_tag}. Check line {line_number}!",
  "Mismatched tags! {wrong_open_tag} and {wrong_close_tag} on line {line_number} don't match, {player_name}.",
  "Wait, {player_name}! {wrong_open_tag} and {wrong_close_tag} on line {line_number} are not partners!",
  "That won't work, {player_name}. {wrong_open_tag} needs its exact match, not {wrong_close_tag} on line {line_number}!",
  "Syntax error, {player_name}! {wrong_open_tag} and {wrong_close_tag} on line {line_number} are totally different tags.",
  "{player_name}, look closely at line {line_number}. {wrong_open_tag} and {wrong_close_tag} don't belong together.",
  "Our code is confused, {player_name}! We paired {wrong_open_tag} with {wrong_close_tag} on line {line_number}.",
  "{player_name}, HTML tags need to mirror each other! {wrong_open_tag} and {wrong_close_tag} on line {line_number} failed us.",
  "Check line {line_number}, {player_name}! {wrong_open_tag} opening and {wrong_close_tag} closing is causing a bug!",
  "Hold on, {player_name}! Opening with {wrong_open_tag} and closing with {wrong_close_tag} on line {line_number} is going to break the layout!",
  "Yikes, {player_name}! {wrong_open_tag} and {wrong_close_tag} are a terrible match. Let's fix line {line_number}.",
  "{player_name}, we can't start a {wrong_open_tag} and end it with a {wrong_close_tag}! Take a look at line {line_number}.",
  "Uh oh! The DOM won't like that, {player_name}. {wrong_open_tag} and {wrong_close_tag} on line {line_number} are completely different.",
  "Line {line_number} is broken, {player_name}! {wrong_close_tag} is definitely not the right closing tag for {wrong_open_tag}.",
  "Hey {player_name}, {wrong_open_tag} is looking for its true partner on line {line_number}, not {wrong_close_tag}!",
  "That's a syntax trap, {player_name}! {wrong_open_tag} doesn't pair with {wrong_close_tag} on line {line_number}.",
  "Whoops! {player_name}, it looks like we tried to close {wrong_open_tag} with {wrong_close_tag} on line {line_number}. Let's correct it!",
  "The browser is going to complain about line {line_number}, {player_name}. {wrong_open_tag} and {wrong_close_tag} just don't go together!",
  "Careful, {player_name}! You opened {wrong_open_tag} but closed with {wrong_close_tag}. Check line {line_number} again.",
  "Hold up! {player_name}, {wrong_open_tag} and {wrong_close_tag} are clashing on line {line_number}.",
  "We have a tag identity crisis on line {line_number}, {player_name}! {wrong_open_tag} cannot turn into {wrong_close_tag}.",
  "A mismatch, {player_name}! {wrong_open_tag} needs a proper closing tag on line {line_number}, {wrong_close_tag} won't cut it.",
  "Nice try, {player_name}, but {wrong_open_tag} and {wrong_close_tag} on line {line_number} is illegal syntax!",
  "Let's untangle line {line_number}, {player_name}. {wrong_open_tag} shouldn't be closed by {wrong_close_tag}.",
  "{player_name}, the code is crying on line {line_number}! {wrong_open_tag} and {wrong_close_tag} are a bad couple.",
  "Alert! {player_name}, {wrong_open_tag} paired with {wrong_close_tag} on line {line_number} is a guaranteed glitch.",
  "We almost had it, {player_name}! But {wrong_open_tag} and {wrong_close_tag} on line {line_number} ruined the combo.",
  "Take another look at line {line_number}, {player_name}. {wrong_open_tag} doesn't recognize {wrong_close_tag}!",
  "Oof, tag collision on line {line_number}! {player_name}, {wrong_open_tag} and {wrong_close_tag} are fighting.",
  "That's not a valid pair, {player_name}! Fix {wrong_open_tag} and {wrong_close_tag} on line {line_number} before we take more damage!",
  "We left {wrong_open_tag} hanging, {player_name}! {wrong_close_tag} on line {line_number} doesn't close it.",
  "Houston, we have a problem on line {line_number}. {player_name}, {wrong_open_tag} and {wrong_close_tag} are mismatched!",
  "Look at line {line_number}, {player_name}. If we open with {wrong_open_tag}, we can't just end with {wrong_close_tag}!",
  "The enemy is laughing at our syntax, {player_name}! {wrong_open_tag} and {wrong_close_tag} on line {line_number} is not a valid combo.",
  "Fix the structure, {player_name}! {wrong_open_tag} requires its exact twin on line {line_number}, not {wrong_close_tag}.",
  "{player_name}, we're giving the parser a headache! {wrong_open_tag} and {wrong_close_tag} on line {line_number} don't align.",
  "Code red, {player_name}! Line {line_number} has {wrong_open_tag} awkwardly paired with {wrong_close_tag}.",
  "Check your pairs, {player_name}! {wrong_open_tag} is definitely not closed by {wrong_close_tag} on line {line_number}.",
  "{player_name}, {wrong_close_tag} is an imposter on line {line_number}! {wrong_open_tag} needs its real closing tag.",
  "That logic is broken, {player_name}! You matched {wrong_open_tag} with {wrong_close_tag} on line {line_number}.",
  "We can't compile that! {player_name}, {wrong_open_tag} and {wrong_close_tag} on line {line_number} are unlinked.",
];
