/**
 * OAuth Configuration for Micomi
 * 
 * Replace the placeholder values with your actual OAuth credentials from:
 * - Google Cloud Console: https://console.cloud.google.com/
 * - Facebook Developer Dashboard: https://developers.facebook.com/
 */

export const OAUTH_CONFIG = {
  GOOGLE: {
    // Web Client ID from Google Cloud Console
    clientId: "459111764902-09uhkdrbfq1tv7gml6dbce3t05ka3jlj.apps.googleusercontent.com",
    scopes: ['profile', 'email'],
  },
  FACEBOOK: {
    // Facebook App ID from Facebook Developer Dashboard
    clientId: "REPLACE_WITH_YOUR_FACEBOOK_APP_ID",
    scopes: ['public_profile', 'email'],
  },
};

/**
 * EXPO_GO_IMPORTANT_NOTE:
 * 
 * When using Expo Go for development:
 * 1. Google OAuth redirect URI is auto-generated by Expo
 * 2. You MUST add the generated URI to Google Cloud Console
 * 3. Check console logs for the exact redirect URI
 * 4. Always use useProxy: true for development
 * 
 * See GOOGLE_OAUTH_SETUP.md for detailed instructions
 */
